### ISSUE TITLE
i can't install gem fashion in windows. 

### ISSUE THREAD

**Issue by mlgiter** [westonplatter/phashion#56]
i tried gem install phashion -v '1.1.1' && bundle install
and get :

mypathto\Ruby2.2.3-x64\lib\ruby\gems\2.2.0\extensions\x64-mingw32\2.2.0\phashion-1.1.1>gem install phashion -v '1.1.1' && bundle install
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing phashion:
        ERROR: Failed to build gem native extension.

    mypathto/Ruby2.2.3-x64/bin/ruby.exe -r ./siteconf20150910-6496-1jd1guo.rb extconf.rb
tar (child): Cannot execute remote shell: No such file or directory
tar (child): mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1/ext/phashion_ext/pHash-0.9.6.tar.gz: Cannot open: I/O error
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Exiting with failure status due to previous errors
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=mypathto/Ruby2.2.3-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:20:in `block in <main>': 'tar xzf mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1' failed (RuntimeError)
        from extconf.rb:14:in `chdir'
        from extconf.rb:14:in `<main>'
tar xzf mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1

extconf failed, exit code 1

Gem files will remain installed in mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1 for inspection.

but in mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1
i have only gem_make.out with content:

mypathto/Ruby2.2.3-x64/bin/ruby.exe -r ./siteconf20150910-9036-14ombai.rb extconf.rb
tar (child): Cannot execute remote shell: No such file or directory
tar (child): mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1/ext/phashion_ext/pHash-0.9.6.tar.gz: Cannot open: I/O error
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Exiting with failure status due to previous errors
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=mypathto/Ruby2.2.3-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:20:in `block in <main>': 'tar xzf mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1' failed (RuntimeError)
	from extconf.rb:14:in `chdir'
	from extconf.rb:14:in `<main>'
tar xzf mypathto/Ruby2.2.3-x64/lib/ruby/gems/2.2.0/gems/phashion-1.1.1/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1

extconf failed, exit code 1

in expression mypathto drive letter sometimes looks like E\, not like E

**Comment by westonplatter** [comment]
@mlgiter can you retry with the new `1.2.0` version that was recently pushed to rubygems?

**Comment by taxen** [comment]
Here is my try on Ruby 2.2.5p319 (2016-04-26 revision 54774) [x64-mingw32], RubyGems 2.6.13

>gem install phashion
Fetching: phashion-1.2.0.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing phashion:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext
C:/Ruby/bin/ruby.exe -r ./siteconf20170911-11160-5qnyo5.rb extconf.rb
tar: Cannot fork: Function not implemented
tar: Error is not recoverable: exiting now
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/bin/$(RUBY_BASE_NAME)
extconf.rb:20:in `block in <main>': 'tar xzf C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1' failed (RuntimeError)
        from extconf.rb:14:in `chdir'
        from extconf.rb:14:in `<main>'
tar xzf C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/phashion-1.2.0/gem_make.out

**Comment by taxen** [comment]
Changed extconf.rb in \ext\phashion_ext line 19 to

    puts(cmd = "gzip -dc #{BUNDLE} | tar -tf - 2>&1")

and got this (under admin privilege)

C:\Ruby\lib\ruby\gems\2.2.0\gems\phashion-1.2.0\ext\phashion_ext>ruby extconf.rb
gzip -dc C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6.tar.gz | tar --force-local -tf - 2>&1
pHash-0.9.6/
pHash-0.9.6/aclocal.m4
pHash-0.9.6/AUTHORS
pHash-0.9.6/bindings/
pHash-0.9.6/ChangeLog
pHash-0.9.6/CImg-1.4.7/
pHash-0.9.6/CImg.h
pHash-0.9.6/config.guess
pHash-0.9.6/config.h.in
pHash-0.9.6/config.sub
pHash-0.9.6/configure
pHash-0.9.6/configure.ac
pHash-0.9.6/COPYING
pHash-0.9.6/depcomp
pHash-0.9.6/examples/
pHash-0.9.6/INSTALL
pHash-0.9.6/install-sh
pHash-0.9.6/libpHash.spec
pHash-0.9.6/ltmain.sh
pHash-0.9.6/m4/
pHash-0.9.6/Makefile.am
pHash-0.9.6/Makefile.in
pHash-0.9.6/missing
pHash-0.9.6/NEWS
pHash-0.9.6/pHash-config.h
pHash-0.9.6/pHash-config.h.in
pHash-0.9.6/pHash.pc.in
pHash-0.9.6/README
pHash-0.9.6/src/
pHash-0.9.6/src/audiophash.cpp
pHash-0.9.6/src/audiophash.h
pHash-0.9.6/src/cimgffmpeg.cpp
pHash-0.9.6/src/cimgffmpeg.h
pHash-0.9.6/src/Makefile.am
pHash-0.9.6/src/Makefile.in
pHash-0.9.6/src/ph_fft.c
pHash-0.9.6/src/ph_fft.h
pHash-0.9.6/src/pHash.cpp
pHash-0.9.6/src/pHash.h
pHash-0.9.6/m4/ax_pthread.m4
pHash-0.9.6/examples/Makefile.am
pHash-0.9.6/examples/Makefile.in
pHash-0.9.6/examples/test_audiophash.cpp
pHash-0.9.6/examples/test_dctvideohash.cpp
pHash-0.9.6/examples/test_imagephash.cpp
pHash-0.9.6/examples/test_mhimagehash.cpp
pHash-0.9.6/examples/test_texthash.cpp
pHash-0.9.6/examples/test_texthash2.cpp
pHash-0.9.6/CImg-1.4.7/CImg.h
pHash-0.9.6/bindings/c_sharp/
pHash-0.9.6/bindings/java/
pHash-0.9.6/bindings/Makefile.am
pHash-0.9.6/bindings/Makefile.in
pHash-0.9.6/bindings/php/
pHash-0.9.6/bindings/php/.cvsignore
pHash-0.9.6/bindings/php/.deps
pHash-0.9.6/bindings/php/.libs/
pHash-0.9.6/bindings/php/acinclude.m4
pHash-0.9.6/bindings/php/aclocal.m4
pHash-0.9.6/bindings/php/build/
pHash-0.9.6/bindings/php/config.guess
pHash-0.9.6/bindings/php/config.h
pHash-0.9.6/bindings/php/config.h.in
pHash-0.9.6/bindings/php/config.log
pHash-0.9.6/bindings/php/config.m4
pHash-0.9.6/bindings/php/config.nice
pHash-0.9.6/bindings/php/config.status
pHash-0.9.6/bindings/php/config.sub
pHash-0.9.6/bindings/php/config.w32
pHash-0.9.6/bindings/php/configure
pHash-0.9.6/bindings/php/configure.in
pHash-0.9.6/bindings/php/CREDITS
pHash-0.9.6/bindings/php/EXPERIMENTAL
pHash-0.9.6/bindings/php/include/
pHash-0.9.6/bindings/php/install-sh
pHash-0.9.6/bindings/php/libtool
pHash-0.9.6/bindings/php/LICENSE
pHash-0.9.6/bindings/php/LICENSE.bak
pHash-0.9.6/bindings/php/ltmain.sh
pHash-0.9.6/bindings/php/Makefile
pHash-0.9.6/bindings/php/Makefile.fragments
pHash-0.9.6/bindings/php/Makefile.global
pHash-0.9.6/bindings/php/Makefile.objects
pHash-0.9.6/bindings/php/manual/
pHash-0.9.6/bindings/php/missing
pHash-0.9.6/bindings/php/mkinstalldirs
pHash-0.9.6/bindings/php/modules/
pHash-0.9.6/bindings/php/package.xml
pHash-0.9.6/bindings/php/package.xml.bak
pHash-0.9.6/bindings/php/package2.xml
pHash-0.9.6/bindings/php/package2.xml.bak
pHash-0.9.6/bindings/php/pHash.cpp
pHash-0.9.6/bindings/php/pHash.cpp.bak
pHash-0.9.6/bindings/php/pHash.dsp
pHash-0.9.6/bindings/php/pHash.la
pHash-0.9.6/bindings/php/pHash.lo
pHash-0.9.6/bindings/php/pHash.xml
pHash-0.9.6/bindings/php/pHash_logos.h
pHash-0.9.6/bindings/php/php_pHash.h
pHash-0.9.6/bindings/php/php_pHash.h.bak
pHash-0.9.6/bindings/php/README
pHash-0.9.6/bindings/php/README.bak
pHash-0.9.6/bindings/php/run-tests.php
pHash-0.9.6/bindings/php/tests/
pHash-0.9.6/bindings/php/tests/ph_audio_dist.phpt
pHash-0.9.6/bindings/php/tests/ph_audiohash.phpt
pHash-0.9.6/bindings/php/tests/ph_compare_text_hashes.phpt
pHash-0.9.6/bindings/php/tests/ph_dct_imagehash.phpt
pHash-0.9.6/bindings/php/tests/ph_dct_videohash.phpt
pHash-0.9.6/bindings/php/tests/ph_image_dist.phpt
pHash-0.9.6/bindings/php/tests/ph_radish_imagehash.phpt
pHash-0.9.6/bindings/php/tests/ph_texthash.phpt
pHash-0.9.6/bindings/php/tests/ph_video_dist.phpt
pHash-0.9.6/bindings/php/modules/pHash.la
pHash-0.9.6/bindings/php/modules/pHash.so
pHash-0.9.6/bindings/php/manual/file-entities.ent
pHash-0.9.6/bindings/php/manual/file-entities.ent.bak
pHash-0.9.6/bindings/php/manual/functions.xml
pHash-0.9.6/bindings/php/manual/functions.xml.bak
pHash-0.9.6/bindings/php/manual/Makefile
pHash-0.9.6/bindings/php/manual/manual.xml.in
pHash-0.9.6/bindings/php/manual/pHash/
pHash-0.9.6/bindings/php/manual/pHash/configure.xml
pHash-0.9.6/bindings/php/manual/pHash/configure.xml.bak
pHash-0.9.6/bindings/php/manual/pHash/constants.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/
pHash-0.9.6/bindings/php/manual/pHash/ini.xml
pHash-0.9.6/bindings/php/manual/pHash/reference.xml
pHash-0.9.6/bindings/php/manual/pHash/reference.xml.bak
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-audio-dist.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-audiohash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-compare-text-hashes.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-dct-imagehash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-dct-imagehash.xml.bak
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-dct-videohash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-image-dist.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-radish-imagehash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-texthash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-video-dist.xml
pHash-0.9.6/bindings/php/build/libtool.m4
pHash-0.9.6/bindings/php/build/mkdep.awk
pHash-0.9.6/bindings/php/build/scan_makefile_in.awk
pHash-0.9.6/bindings/php/build/shtool
pHash-0.9.6/bindings/php/.libs/pHash.la
pHash-0.9.6/bindings/php/.libs/pHash.lai
pHash-0.9.6/bindings/php/.libs/pHash.o
pHash-0.9.6/bindings/php/.libs/pHash.so
pHash-0.9.6/bindings/java/Makefile.am
pHash-0.9.6/bindings/java/Makefile.in
pHash-0.9.6/bindings/java/org/
pHash-0.9.6/bindings/java/pHash-jni.cpp
pHash-0.9.6/bindings/java/pHash-jni.h
pHash-0.9.6/bindings/java/pHash_MVPTree.h
pHash-0.9.6/bindings/java/README
pHash-0.9.6/bindings/java/org/phash/
pHash-0.9.6/bindings/java/org/phash/AudioHash.java
pHash-0.9.6/bindings/java/org/phash/DCTImageHash.java
pHash-0.9.6/bindings/java/org/phash/Hash.java
pHash-0.9.6/bindings/java/org/phash/ImageHash.java
pHash-0.9.6/bindings/java/org/phash/MHImageHash.java
pHash-0.9.6/bindings/java/org/phash/MVPTree.java
pHash-0.9.6/bindings/java/org/phash/pHash.java
pHash-0.9.6/bindings/java/org/phash/RadialImageHash.java
pHash-0.9.6/bindings/java/org/phash/TextHash.java
pHash-0.9.6/bindings/java/org/phash/VideoHash.java
pHash-0.9.6/bindings/c_sharp/pHash.cs
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/bin/$(RUBY_BASE_NAME)
extconf.rb:22:in `chdir': No such file or directory @ dir_chdir - C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6 (Errno::ENOENT)
        from extconf.rb:22:in `block in <main>'
        from extconf.rb:14:in `chdir'
        from extconf.rb:14:in `<main>'

**Comment by taxen** [comment]
After manually extracting the tarball and did the same...

C:\Ruby\lib\ruby\gems\2.2.0\gems\phashion-1.2.0\ext\phashion_ext>ruby extconf.rb
gzip -dc C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6.tar.gz | tar --force-local -tf - 2>&1
pHash-0.9.6/
pHash-0.9.6/aclocal.m4
pHash-0.9.6/AUTHORS
pHash-0.9.6/bindings/
pHash-0.9.6/ChangeLog
pHash-0.9.6/CImg-1.4.7/
pHash-0.9.6/CImg.h
pHash-0.9.6/config.guess
pHash-0.9.6/config.h.in
pHash-0.9.6/config.sub
pHash-0.9.6/configure
pHash-0.9.6/configure.ac
pHash-0.9.6/COPYING
pHash-0.9.6/depcomp
pHash-0.9.6/examples/
pHash-0.9.6/INSTALL
pHash-0.9.6/install-sh
pHash-0.9.6/libpHash.spec
pHash-0.9.6/ltmain.sh
pHash-0.9.6/m4/
pHash-0.9.6/Makefile.am
pHash-0.9.6/Makefile.in
pHash-0.9.6/missing
pHash-0.9.6/NEWS
pHash-0.9.6/pHash-config.h
pHash-0.9.6/pHash-config.h.in
pHash-0.9.6/pHash.pc.in
pHash-0.9.6/README
pHash-0.9.6/src/
pHash-0.9.6/src/audiophash.cpp
pHash-0.9.6/src/audiophash.h
pHash-0.9.6/src/cimgffmpeg.cpp
pHash-0.9.6/src/cimgffmpeg.h
pHash-0.9.6/src/Makefile.am
pHash-0.9.6/src/Makefile.in
pHash-0.9.6/src/ph_fft.c
pHash-0.9.6/src/ph_fft.h
pHash-0.9.6/src/pHash.cpp
pHash-0.9.6/src/pHash.h
pHash-0.9.6/m4/ax_pthread.m4
pHash-0.9.6/examples/Makefile.am
pHash-0.9.6/examples/Makefile.in
pHash-0.9.6/examples/test_audiophash.cpp
pHash-0.9.6/examples/test_dctvideohash.cpp
pHash-0.9.6/examples/test_imagephash.cpp
pHash-0.9.6/examples/test_mhimagehash.cpp
pHash-0.9.6/examples/test_texthash.cpp
pHash-0.9.6/examples/test_texthash2.cpp
pHash-0.9.6/CImg-1.4.7/CImg.h
pHash-0.9.6/bindings/c_sharp/
pHash-0.9.6/bindings/java/
pHash-0.9.6/bindings/Makefile.am
pHash-0.9.6/bindings/Makefile.in
pHash-0.9.6/bindings/php/
pHash-0.9.6/bindings/php/.cvsignore
pHash-0.9.6/bindings/php/.deps
pHash-0.9.6/bindings/php/.libs/
pHash-0.9.6/bindings/php/acinclude.m4
pHash-0.9.6/bindings/php/aclocal.m4
pHash-0.9.6/bindings/php/build/
pHash-0.9.6/bindings/php/config.guess
pHash-0.9.6/bindings/php/config.h
pHash-0.9.6/bindings/php/config.h.in
pHash-0.9.6/bindings/php/config.log
pHash-0.9.6/bindings/php/config.m4
pHash-0.9.6/bindings/php/config.nice
pHash-0.9.6/bindings/php/config.status
pHash-0.9.6/bindings/php/config.sub
pHash-0.9.6/bindings/php/config.w32
pHash-0.9.6/bindings/php/configure
pHash-0.9.6/bindings/php/configure.in
pHash-0.9.6/bindings/php/CREDITS
pHash-0.9.6/bindings/php/EXPERIMENTAL
pHash-0.9.6/bindings/php/include/
pHash-0.9.6/bindings/php/install-sh
pHash-0.9.6/bindings/php/libtool
pHash-0.9.6/bindings/php/LICENSE
pHash-0.9.6/bindings/php/LICENSE.bak
pHash-0.9.6/bindings/php/ltmain.sh
pHash-0.9.6/bindings/php/Makefile
pHash-0.9.6/bindings/php/Makefile.fragments
pHash-0.9.6/bindings/php/Makefile.global
pHash-0.9.6/bindings/php/Makefile.objects
pHash-0.9.6/bindings/php/manual/
pHash-0.9.6/bindings/php/missing
pHash-0.9.6/bindings/php/mkinstalldirs
pHash-0.9.6/bindings/php/modules/
pHash-0.9.6/bindings/php/package.xml
pHash-0.9.6/bindings/php/package.xml.bak
pHash-0.9.6/bindings/php/package2.xml
pHash-0.9.6/bindings/php/package2.xml.bak
pHash-0.9.6/bindings/php/pHash.cpp
pHash-0.9.6/bindings/php/pHash.cpp.bak
pHash-0.9.6/bindings/php/pHash.dsp
pHash-0.9.6/bindings/php/pHash.la
pHash-0.9.6/bindings/php/pHash.lo
pHash-0.9.6/bindings/php/pHash.xml
pHash-0.9.6/bindings/php/pHash_logos.h
pHash-0.9.6/bindings/php/php_pHash.h
pHash-0.9.6/bindings/php/php_pHash.h.bak
pHash-0.9.6/bindings/php/README
pHash-0.9.6/bindings/php/README.bak
pHash-0.9.6/bindings/php/run-tests.php
pHash-0.9.6/bindings/php/tests/
pHash-0.9.6/bindings/php/tests/ph_audio_dist.phpt
pHash-0.9.6/bindings/php/tests/ph_audiohash.phpt
pHash-0.9.6/bindings/php/tests/ph_compare_text_hashes.phpt
pHash-0.9.6/bindings/php/tests/ph_dct_imagehash.phpt
pHash-0.9.6/bindings/php/tests/ph_dct_videohash.phpt
pHash-0.9.6/bindings/php/tests/ph_image_dist.phpt
pHash-0.9.6/bindings/php/tests/ph_radish_imagehash.phpt
pHash-0.9.6/bindings/php/tests/ph_texthash.phpt
pHash-0.9.6/bindings/php/tests/ph_video_dist.phpt
pHash-0.9.6/bindings/php/modules/pHash.la
pHash-0.9.6/bindings/php/modules/pHash.so
pHash-0.9.6/bindings/php/manual/file-entities.ent
pHash-0.9.6/bindings/php/manual/file-entities.ent.bak
pHash-0.9.6/bindings/php/manual/functions.xml
pHash-0.9.6/bindings/php/manual/functions.xml.bak
pHash-0.9.6/bindings/php/manual/Makefile
pHash-0.9.6/bindings/php/manual/manual.xml.in
pHash-0.9.6/bindings/php/manual/pHash/
pHash-0.9.6/bindings/php/manual/pHash/configure.xml
pHash-0.9.6/bindings/php/manual/pHash/configure.xml.bak
pHash-0.9.6/bindings/php/manual/pHash/constants.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/
pHash-0.9.6/bindings/php/manual/pHash/ini.xml
pHash-0.9.6/bindings/php/manual/pHash/reference.xml
pHash-0.9.6/bindings/php/manual/pHash/reference.xml.bak
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-audio-dist.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-audiohash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-compare-text-hashes.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-dct-imagehash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-dct-imagehash.xml.bak
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-dct-videohash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-image-dist.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-radish-imagehash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-texthash.xml
pHash-0.9.6/bindings/php/manual/pHash/functions/ph-video-dist.xml
pHash-0.9.6/bindings/php/build/libtool.m4
pHash-0.9.6/bindings/php/build/mkdep.awk
pHash-0.9.6/bindings/php/build/scan_makefile_in.awk
pHash-0.9.6/bindings/php/build/shtool
pHash-0.9.6/bindings/php/.libs/pHash.la
pHash-0.9.6/bindings/php/.libs/pHash.lai
pHash-0.9.6/bindings/php/.libs/pHash.o
pHash-0.9.6/bindings/php/.libs/pHash.so
pHash-0.9.6/bindings/java/Makefile.am
pHash-0.9.6/bindings/java/Makefile.in
pHash-0.9.6/bindings/java/org/
pHash-0.9.6/bindings/java/pHash-jni.cpp
pHash-0.9.6/bindings/java/pHash-jni.h
pHash-0.9.6/bindings/java/pHash_MVPTree.h
pHash-0.9.6/bindings/java/README
pHash-0.9.6/bindings/java/org/phash/
pHash-0.9.6/bindings/java/org/phash/AudioHash.java
pHash-0.9.6/bindings/java/org/phash/DCTImageHash.java
pHash-0.9.6/bindings/java/org/phash/Hash.java
pHash-0.9.6/bindings/java/org/phash/ImageHash.java
pHash-0.9.6/bindings/java/org/phash/MHImageHash.java
pHash-0.9.6/bindings/java/org/phash/MVPTree.java
pHash-0.9.6/bindings/java/org/phash/pHash.java
pHash-0.9.6/bindings/java/org/phash/RadialImageHash.java
pHash-0.9.6/bindings/java/org/phash/TextHash.java
pHash-0.9.6/bindings/java/org/phash/VideoHash.java
pHash-0.9.6/bindings/c_sharp/pHash.cs
env CXXFLAGS=' -pthread' CFLAGS=' -IC:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/include  -LC:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib  -x c++ ' LDFLAGS=' -LC:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. ' ./configure --prefix=C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext --disable-audio-hash --disable-video-hash --disable-shared --with-pic 2>&1
env: -pthread': No such file or directory
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/bin/$(RUBY_BASE_NAME)
extconf.rb:24:in `block (2 levels) in <main>': 'env CXXFLAGS=' -pthread' CFLAGS=' -IC:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/include  -LC:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib  -x c++ ' LDFLAGS=' -LC:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. ' ./configure --prefix=C:/Ruby/lib/ruby/gems/2.2.0/gems/phashion-1.2.0/ext/phashion_ext --disable-audio-hash --disable-video-hash --disable-shared --with-pic 2>&1' failed (RuntimeError)
        from extconf.rb:22:in `chdir'
        from extconf.rb:22:in `block in <main>'
        from extconf.rb:14:in `chdir'
        from extconf.rb:14:in `<main>'
