### ISSUE TITLE
Install fails on OS X 10.5 Leopard (PowerPC)

### ISSUE THREAD

**Issue by duffyjp** [westonplatter/phashion#57]
I get the same message as #53 but I have the libraries installed...

```bash 
$ brew list 
autoconf        freetype    jpegoptim    mysql      sha2
automake        gdbm        libgpg-error openssl    smartmontools
bash            git         libksba      optipng    sqlite
cctools         gnupg       libpng       pidof      xz
cmake           htop-osx    libtiff      pkg-config zlib
curl            imagemagick libtool      python
curl-ca-bundle  jpeg        libyaml      readline
```
Any suggestions would be appreciated. 10.5 is the highest you can go on PowerPC.

Here is the full output:
```
$ gem install phashion
Building native extensions.  This could take a while...
ERROR:  Error installing phashion:
	ERROR: Failed to build gem native extension.

    /Users/jacob/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151113-20252-15qqwtb.rb extconf.rb
tar xzf /Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1
env CXXFLAGS=' -pthread' CFLAGS=' -I/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/include  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib  -x c++ ' LDFLAGS=' -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib ' ./configure --prefix=/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext --disable-audio-hash --disable-video-hash --disable-shared --with-pic 2>&1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... unsupported
checking dependency style of gcc... gcc3
checking for /etc/gentoo-release... no
checking for /etc/redhat-release... no
checking for /etc/slackware-version... no
checking for /etc/debian_version... no
checking for /etc/SuSErelease... no
checking build system type... powerpc-apple-darwin9.8.0
checking host system type... powerpc-apple-darwin9.8.0
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether ln -s works... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld
checking if the linker (/usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -p
checking the name lister (/usr/bin/nm -p) interface... BSD nm
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert powerpc-apple-darwin9.8.0 file names to powerpc-apple-darwin9.8.0 format... func_convert_file_noop
checking how to convert powerpc-apple-darwin9.8.0 file names to toolchain format... func_convert_file_noop
checking for /usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -p output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... ld: unknown option: -force_load
no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin9.8.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld
checking if the linker (/usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld) is GNU ld... no
checking whether the g++ linker (/usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/libexec/gcc/powerpc-apple-darwin9/4.0.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin9.8.0 dyld
checking how to hardcode library paths into programs... immediate

*** Configuring image hash ***

checking CImg.h usability... no
checking CImg.h presence... no
checking for CImg.h... no
checking whether CImg.h is in the current or src directory.... yes
checking for png_create_read_struct in -lpng... no
checking for jpeg_read_header in -ljpeg... yes
checking for fftw_plan_dft_r2c_1d in -lfftw3... no
checking for size_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for uint64_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating examples/Makefile
config.status: creating pHash.pc
config.status: creating bindings/Makefile
config.status: creating bindings/java/Makefile
config.status: creating config.h
config.status: creating pHash-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make || true 2>&1
make  all-recursive
Making all in src
/bin/sh ../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/local/include -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT pHash.lo -MD -MP -MF .deps/pHash.Tpo -c -o pHash.lo pHash.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -Dcimg_use_jpeg -pthread -ffast-math -O3 -MT pHash.lo -MD -MP -MF .deps/pHash.Tpo -c pHash.cpp  -fno-common -DPIC -o pHash.o
mv -f .deps/pHash.Tpo .deps/pHash.Plo
/bin/sh ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3 -no-undefined -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o libpHash.la -rpath /Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib pHash.lo    -ljpeg
libtool: link: ar cru .libs/libpHash.a  pHash.o
libtool: link: ranlib .libs/libpHash.a
libtool: link: ( cd ".libs" && rm -f "libpHash.la" && ln -s "../libpHash.la" "libpHash.la" )
Making all in bindings
make[3]: Nothing to be done for `all-am'.
Making all in examples
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_texthash.o -MD -MP -MF .deps/test_texthash.Tpo -c -o test_texthash.o test_texthash.cpp
mv -f .deps/test_texthash.Tpo .deps/test_texthash.Po
/bin/sh ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o test_texthash test_texthash.o ../src/libpHash.la -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -fstack-protector -o test_texthash test_texthash.o -Wl,-bind_at_load  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib ../src/.libs/libpHash.a -ljpeg -pthread
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_texthash2.o -MD -MP -MF .deps/test_texthash2.Tpo -c -o test_texthash2.o test_texthash2.cpp
mv -f .deps/test_texthash2.Tpo .deps/test_texthash2.Po
/bin/sh ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o test_texthash2 test_texthash2.o ../src/libpHash.la -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -fstack-protector -o test_texthash2 test_texthash2.o -Wl,-bind_at_load  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib ../src/.libs/libpHash.a -ljpeg -pthread
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_imagephash.o -MD -MP -MF .deps/test_imagephash.Tpo -c -o test_imagephash.o test_imagephash.cpp
mv -f .deps/test_imagephash.Tpo .deps/test_imagephash.Po
/bin/sh ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o test_image test_imagephash.o ../src/libpHash.la -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -fstack-protector -o test_image test_imagephash.o -Wl,-bind_at_load  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib ../src/.libs/libpHash.a -ljpeg -pthread
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_mhimagehash.o -MD -MP -MF .deps/test_mhimagehash.Tpo -c -o test_mhimagehash.o test_mhimagehash.cpp
mv -f .deps/test_mhimagehash.Tpo .deps/test_mhimagehash.Po
/bin/sh ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o test_mhimagehash test_mhimagehash.o ../src/libpHash.la -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -fstack-protector -o test_mhimagehash test_mhimagehash.o -Wl,-bind_at_load  -L/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib -L/usr/local/lib -L. -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib ../src/.libs/libpHash.a -ljpeg -pthread
make[2]: Nothing to be done for `all-am'.
make install || true 2>&1
Making install in src
 .././install-sh -c -d '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libpHash.la '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib'
libtool: install: /usr/bin/install -c .libs/libpHash.lai /Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib/libpHash.la
libtool: install: /usr/bin/install -c .libs/libpHash.a /Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib/libpHash.a
libtool: install: chmod 644 /Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib/libpHash.a
libtool: install: ranlib /Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib/libpHash.a
 .././install-sh -c -d '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/include'
 /usr/bin/install -c -m 644 pHash.h '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/include'
Making install in bindings
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in examples
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
 ./install-sh -c -d '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/include'
 /usr/bin/install -c -m 644 pHash-config.h '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/include'
 ./install-sh -c -d '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib/pkgconfig'
 /usr/bin/install -c -m 644 pHash.pc '/Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1/ext/phashion_ext/lib/pkgconfig'
mv CImg.h ../include 2>&1
checking for sqlite3ext.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/jacob/.rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
/Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /Users/jacob/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
	from extconf.rb:46:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/jacob/.rvm/gems/ruby-2.2.3/gems/phashion-1.1.1 for inspection.
Results logged to /Users/jacob/.rvm/gems/ruby-2.2.3/extensions/powerpc-darwin-9/2.2.0/phashion-1.1.1/gem_make.out
```

**Comment by duffyjp** [comment]
I'm slowing making progress.  Problem #1 appears to be with tigerbrew.  The recipe for libpng doesn't symlink to /usr/local/lib and /usr/local/include stating OS X already provides a version, except it doesn't, at least on 10.5.

I'll fix that recipe in tigerbrew, for now I manually linked the Cellar libpng.dylib libpng.a to lib and the .h files to include.

Now I'm getting this:
```
checking for sqlite3ext.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling phashion_ext.c
phashion_ext.c: In function ‘void hamming_distance(sqlite3_context*, int, sqlite3_value**)’:
phashion_ext.c:121: error: ‘sqlite3_int64’ was not declared in this scope
phashion_ext.c:121: error: expected `;' before ‘hashes’
phashion_ext.c:127: error: ‘hashes’ was not declared in this scope
phashion_ext.c:129: error: ‘hashes’ was not declared in this scope
phashion_ext.c:133: error: ‘hashes’ was not declared in this scope
make: *** [phashion_ext.o] Error 1

make failed, exit code 2
```

**Comment by duffyjp** [comment]
### SOLVED

I was able to install Phashion 1.0.6 (pre SQLite) just fine, so I looked into that a little more closely.  The sqlite provided by OS X 10.5 is understandable outdated, but homebrew doesn't symlink when the system includes an older version of something.

With these two lines everything works fine:
```bash
brew link --force libpng
brew link --force sqlite
```
