### ISSUE TITLE
Ubuntu 18.04 LTS (ruby 2.5.1p57) fails to require phashion_ext.so

### ISSUE THREAD

**Issue by Korkey128k** [westonplatter/phashion#74]
Install appears to work fine, but when you try to require phashion, it fails.

### Here is the complete `gem install phashion --verbose`
```
host:~# gem install phashion --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=phashion
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
/var/lib/gems/2.5.0/gems/phashion-1.2.0/.document
/var/lib/gems/2.5.0/gems/phashion-1.2.0/.gitignore
/var/lib/gems/2.5.0/gems/phashion-1.2.0/.travis.yml
/var/lib/gems/2.5.0/gems/phashion-1.2.0/CHANGES.md
/var/lib/gems/2.5.0/gems/phashion-1.2.0/Gemfile
/var/lib/gems/2.5.0/gems/phashion-1.2.0/LICENSE
/var/lib/gems/2.5.0/gems/phashion-1.2.0/README.md
/var/lib/gems/2.5.0/gems/phashion-1.2.0/Rakefile
/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/extconf.rb
/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6.tar.gz
/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/phashion_ext.c
/var/lib/gems/2.5.0/gems/phashion-1.2.0/lib/phashion.rb
/var/lib/gems/2.5.0/gems/phashion-1.2.0/lib/phashion/version.rb
/var/lib/gems/2.5.0/gems/phashion-1.2.0/phashion.gemspec
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/gif/Broccoli_Super_Food.gif
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/helper.rb
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/86x86-0a1e.jpeg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/86x86-83d6.jpeg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/86x86-a855.jpeg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.100px.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.bounding-box.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.bw.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.color-corrected.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.horizontal-flip.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.lossy.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/Broccoli_Super_Food.rotate5cw.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/avatar.jpg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/b32aade8c590e2d776c24f35868f0c7a588f51e1.jpeg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/df9cc82f5b32d7463f36620c61854fde9d939f7f.jpeg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/jpg/e7397898a7e395c2524978a5e64de0efabf08290.jpeg
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/png/Broccoli_Super_Food.png
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/png/grass.png
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/png/linux.png
/var/lib/gems/2.5.0/gems/phashion-1.2.0/test/test_phashion.rb
Building native extensions. This could take a while...
current directory: /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext
/usr/bin/ruby2.5 -r ./siteconf20180508-32175-1dytk2q.rb extconf.rb
tar xzf /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6.tar.gz 2>&1
env CXXFLAGS=' -pthread' CFLAGS=' -I/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib  -x c++ ' LDFLAGS=' -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic' ./configure --prefix=/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext --disable-audio-hash --disable-video-hash --disable-shared --with-pic 2>&1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... unsupported
checking dependency style of gcc... gcc3
checking for /etc/gentoo-release... no
checking for /etc/redhat-release... no
checking for /etc/slackware-version... no
checking for /etc/debian_version... yes
checking for /etc/SuSErelease... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether ln -s works... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/x86_64-linux-gnu-ld
checking if the linker (/usr/bin/x86_64-linux-gnu-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/x86_64-linux-gnu-ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/x86_64-linux-gnu-ld -m elf_x86_64
checking if the linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/x86_64-linux-gnu-ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate

*** Configuring image hash ***

checking CImg.h usability... no
checking CImg.h presence... no
checking for CImg.h... no
checking whether CImg.h is in the current or src directory.... yes
checking for png_create_read_struct in -lpng... yes
checking for jpeg_read_header in -ljpeg... yes
checking for fftw_plan_dft_r2c_1d in -lfftw3... no
checking for size_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for uint64_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating examples/Makefile
config.status: creating pHash.pc
config.status: creating bindings/Makefile
config.status: creating bindings/java/Makefile
config.status: creating config.h
config.status: creating pHash-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make || true 2>&1
make  all-recursive
make[1]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
Making all in src
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/src'
/bin/bash ../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT pHash.lo -MD -MP -MF .deps/pHash.Tpo -c -o pHash.lo pHash.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg -pthread -ffast-math -O3 -MT pHash.lo -MD -MP -MF .deps/pHash.Tpo -c pHash.cpp  -fPIC -DPIC -o pHash.o
mv -f .deps/pHash.Tpo .deps/pHash.Plo
/bin/bash ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3 -no-undefined -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/local/lib -o libpHash.la -rpath /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib pHash.lo    -lpng -ljpeg
libtool: link: ar cru .libs/libpHash.a  pHash.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libpHash.a
libtool: link: ( cd ".libs" && rm -f "libpHash.la" && ln -s "../libpHash.la" "libpHash.la" )
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/src'
Making all in bindings
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[3]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
Making all in examples
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/examples'
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_texthash.o -MD -MP -MF .deps/test_texthash.Tpo -c -o test_texthash.o test_texthash.cpp
mv -f .deps/test_texthash.Tpo .deps/test_texthash.Po
/bin/bash ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/local/lib -o test_texthash test_texthash.o ../src/libpHash.la -lpng -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -Wl,-z -Wl,now -fstack-protector -rdynamic -Wl,-export-dynamic -o test_texthash test_texthash.o  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. ../src/.libs/libpHash.a -lpng -ljpeg -pthread
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_texthash2.o -MD -MP -MF .deps/test_texthash2.Tpo -c -o test_texthash2.o test_texthash2.cpp
mv -f .deps/test_texthash2.Tpo .deps/test_texthash2.Po
/bin/bash ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/local/lib -o test_texthash2 test_texthash2.o ../src/libpHash.la -lpng -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -Wl,-z -Wl,now -fstack-protector -rdynamic -Wl,-export-dynamic -o test_texthash2 test_texthash2.o  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. ../src/.libs/libpHash.a -lpng -ljpeg -pthread
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_imagephash.o -MD -MP -MF .deps/test_imagephash.Tpo -c -o test_imagephash.o test_imagephash.cpp
mv -f .deps/test_imagephash.Tpo .deps/test_imagephash.Po
/bin/bash ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/local/lib -o test_image test_imagephash.o ../src/libpHash.la -lpng -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -Wl,-z -Wl,now -fstack-protector -rdynamic -Wl,-export-dynamic -o test_image test_imagephash.o  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. ../src/.libs/libpHash.a -lpng -ljpeg -pthread
g++ -DHAVE_CONFIG_H -I. -I.. -I../src  -I/usr/local/include -Dcimg_use_png -Dcimg_use_jpeg  -pthread -ffast-math -O3 -MT test_mhimagehash.o -MD -MP -MF .deps/test_mhimagehash.Tpo -c -o test_mhimagehash.o test_mhimagehash.cpp
mv -f .deps/test_mhimagehash.Tpo .deps/test_mhimagehash.Po
/bin/bash ../libtool --tag=CXX   --mode=link g++  -pthread -ffast-math -O3  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -L/usr/local/lib -o test_mhimagehash test_mhimagehash.o ../src/libpHash.la -lpng -ljpeg
libtool: link: g++ -pthread -ffast-math -O3 -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -Wl,-z -Wl,now -fstack-protector -rdynamic -Wl,-export-dynamic -o test_mhimagehash test_mhimagehash.o  -L/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib -L/usr/local/lib -L. ../src/.libs/libpHash.a -lpng -ljpeg -pthread
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/examples'
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
make[1]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
make install || true 2>&1
Making install in src
make[1]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/src'
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/src'
 /bin/mkdir -p '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libpHash.la '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib'
libtool: install: /usr/bin/install -c .libs/libpHash.lai /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib/libpHash.la
libtool: install: /usr/bin/install -c .libs/libpHash.a /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib/libpHash.a
libtool: install: chmod 644 /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib/libpHash.a
libtool: install: ranlib /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib/libpHash.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin" ldconfig -n /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include'
 /usr/bin/install -c -m 644 pHash.h '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include'
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/src'
make[1]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/src'
Making install in bindings
make[1]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[3]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
make[1]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/bindings'
Making install in examples
make[1]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/examples'
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/examples'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/examples'
make[1]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6/examples'
make[1]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
make[2]: Entering directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include'
 /usr/bin/install -c -m 644 pHash-config.h '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include'
 /bin/mkdir -p '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib/pkgconfig'
 /usr/bin/install -c -m 644 pHash.pc '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/lib/pkgconfig'
make[2]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
make[1]: Leaving directory '/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6'
mv CImg.h ../include 2>&1
checking for sqlite3ext.h... yes
creating Makefile
current directory: /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext
make "DESTDIR=" clean
current directory: /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext
make "DESTDIR="
compiling phashion_ext.c
In file included from /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include/pHash.h:50:0,
                 from phashion_ext.c:2:
/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include/CImg.h:5120:55: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
           std::fprintf(cimg::output()," (%s, %s)\n\n",__DATE__,__TIME__);
                                                       ^~~~~~~~
/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include/CImg.h:5120:64: warning: macro "__TIME__" might prevent reproducible builds [-Wdate-time]
           std::fprintf(cimg::output()," (%s, %s)\n\n",__DATE__,__TIME__);
                                                                ^~~~~~~~
/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include/CImg.h:5213:35: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
                    cimg::t_normal,__DATE__,__TIME__);
                                   ^~~~~~~~
/var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext/include/CImg.h:5213:44: warning: macro "__TIME__" might prevent reproducible builds [-Wdate-time]
                    cimg::t_normal,__DATE__,__TIME__);
                                            ^~~~~~~~
linking shared-object phashion_ext.so
current directory: /var/lib/gems/2.5.0/gems/phashion-1.2.0/ext/phashion_ext
make "DESTDIR=" install
/usr/bin/install -c -m 0755 phashion_ext.so ./.gem.20180508-32175-1rh8t34

Successfully installed phashion-1.2.0
Parsing documentation for phashion-1.2.0
Parsing sources...
100% [17/17]  lib/phashion_ext.so                    
Installing ri documentation for phashion-1.2.0
Done installing documentation for phashion after 1 seconds
1 gem installed
```

### Here is an example of starting an irb and requiring phashion
```
host:~# irb
irb(main):001:0> require 'phashion'
Traceback (most recent call last):
        8: from /usr/bin/irb:11:in `<main>'
        7: from (irb):1
        6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        3: from /var/lib/gems/2.5.0/gems/phashion-1.2.0/lib/phashion.rb:57:in `<top (required)>'
        2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
LoadError (/var/lib/gems/2.5.0/gems/phashion-1.2.0/lib/phashion_ext.so: undefined symbol: _ZGVbN2v_cos - /var/lib/gems/2.5.0/gems/phashion-1.2.0/lib/phashion_ext.so)
```

**Comment by Korkey128k** [comment]
# Update

No issues when compiling from source or using `rbenv`, this seems to be an issue with the `apt-get` package, closing.

**Comment by westonplatter** [comment]
@Korkey128k thanks for posting the issue and closing when you found it was a non-issue. Happy to look into it if you hit other issues.

**Comment by Korkey128k** [comment]
No problem!
👍

**Comment by ricardovsilva** [comment]
I'm still having problems with that. I didn't get the issue with apt-get package, what package? Can you, please, clarify?

**Comment by Korkey128k** [comment]
@ricardovsilva It's the `ruby2.5` package you install via `apt install`

**Comment by skrivy** [comment]
Debian 12, ruby 3.1 has this issue as well.

```
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': /var/lib/gems/3.1.0/gems/phashion-1.2.0/lib/phashion_ext.so: undefined symbol: _ZGVbN2v_cos - /var/lib/gems/3.1.0/gems/phashion-1.2.0/lib/phashion_ext.so (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.1.0/gems/phashion-1.2.0/lib/phashion.rb:57:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from a.rb:1:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- phashion (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from a.rb:1:in `<main>'
```

Sounds like some missing dependency.
