### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by faustoct** [westonplatter/phashion#77]
Gemfile `gem 'phashion'`
`bundle install`

Fetching phashion 1.2.0
Installing phashion 1.2.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext
/Users/fausto/.rvm/rubies/ruby-2.5.1/bin/ruby -r
./siteconf20190424-59758-1y02cl8.rb extconf.rb
tar xzf
/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6.tar.gz
2>&1
env CXXFLAGS=' -pthread' CFLAGS='
-I/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/include
-L/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/lib
-L/usr/local/lib  -x c++ ' LDFLAGS='
-L/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/lib
-L/usr/local/lib -L. -fstack-protector -L/usr/local/lib
-L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib
-L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib
-L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib
-L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib' ./configure
--prefix=/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext
--disable-audio-hash --disable-video-hash --disable-shared --with-pic 2>&1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking for g++... g++
checking whether the C++ compiler works... no
configure: error: in
`/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/pHash-0.9.6':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/fausto/.rvm/rubies/ruby-2.5.1/bin/$(RUBY_BASE_NAME)
extconf.rb:24:in `block (2 levels) in <main>': 'env CXXFLAGS=' -pthread'
CFLAGS='
-I/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/include
-L/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/lib
-L/usr/local/lib  -x c++ ' LDFLAGS='
-L/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext/lib
-L/usr/local/lib -L. -fstack-protector -L/usr/local/lib
-L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib
-L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib
-L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib
-L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib' ./configure
--prefix=/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0/ext/phashion_ext
--disable-audio-hash --disable-video-hash --disable-shared --with-pic 2>&1'
failed (RuntimeError)
	from extconf.rb:22:in `chdir'
	from extconf.rb:22:in `block in <main>'
	from extconf.rb:14:in `chdir'
	from extconf.rb:14:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
/Users/fausto/.rvm/gems/ruby-2.5.1/gems/phashion-1.2.0 for inspection.
Results logged to
/Users/fausto/.rvm/gems/ruby-2.5.1/extensions/x86_64-darwin-17/2.5.0/phashion-1.2.0/gem_make.out

An error occurred while installing phashion (1.2.0), and Bundler cannot
continue.
Make sure that `gem install phashion -v '1.2.0' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  phashion

**Comment by faustoct** [comment]
The same running on heroku

**Comment by faustoct** [comment]
temporarily moved to https://github.com/Nakilon/dhash-vips
